// The circle of fifths is the cycle generated by adding 7 semitones mod 12.
import { mod12, pitchClassName } from './pitch.js'

/** Pitch classes in circle-of-fifths order starting from `start`. */
export function circleOfFifths(start = 0) {
  return Array.from({ length: 12 }, (_, k) => mod12(start + 7 * k))
}

/** Steps clockwise from C (0..11) for a pitch class: pc = 7k mod 12 ⇒ k = 7·pc mod 12. */
export const fifthsFromC = (pc) => mod12(7 * pc)

/**
 * Key signature of a major key. Keys 1–5 steps clockwise use sharps, 7–11 use
 * flats, and the 6-step key (F♯ / G♭) is shown both ways.
 */
export function keySignature(pc) {
  const k = fifthsFromC(pc)
  if (k === 0) return { sharps: 0, flats: 0, label: 'no sharps or flats', name: 'C' }
  if (k === 6) return { sharps: 6, flats: 6, label: '6♯ or 6♭', name: 'F♯ / G♭' }
  if (k < 6) return { sharps: k, flats: 0, label: `${k}♯`, name: pitchClassName(pc) }
  return { sharps: 0, flats: 12 - k, label: `${12 - k}♭`, name: pitchClassName(pc, { flats: true }) }
}

/** Relative minor of a major key sits a minor 3rd (3 semitones) below. */
export const relativeMinor = (pc) => mod12(pc - 3)

export const SHARP_ORDER = ['F', 'C', 'G', 'D', 'A', 'E', 'B']
export const FLAT_ORDER = ['B', 'E', 'A', 'D', 'G', 'C', 'F']
