// The curated series and their lessons, in teaching order. Plain data, so the
// checker (scripts/check_notebook_series.mjs) can read it outside Vite.
//
// A lesson's text lives in `./<series dir>/<slug>.md`; until that file exists
// the lesson shows as "coming soon". Its id is `<prefix>-<slug>` and is a
// progress key: once a lesson ships, never rename its slug. Reordering lessons
// here is safe. Curriculum and lesson standard: docs/notebook-series-curriculum.md.

const series = (id, dir, prefix, title, blurb, lessons) => ({
  id,
  dir,
  title,
  blurb,
  lessons: lessons.map(([slug, lessonTitle], i) => ({
    id: `${prefix}-${slug}`,
    slug,
    number: i + 1,
    title: lessonTitle,
  })),
})

export const SERIES_MANIFEST = [
  series('python', 'python', 'py', 'Python from Zero',
    'No experience needed. Start here before Machine Learning or Algorithms.', [
      ['running-code', 'Running code'],
      ['numbers-and-variables', 'Numbers and variables'],
      ['strings', 'Strings'],
      ['decisions', 'Decisions'],
      ['lists', 'Lists'],
      ['for-loops', 'for loops'],
      ['while-loops', 'while loops'],
      ['functions', 'Functions'],
      ['functions-in-depth', 'Functions in depth'],
      ['dictionaries', 'Dictionaries'],
      ['tuples-and-sets', 'Tuples and sets'],
      ['names-and-references', 'Names and references'],
      ['comprehensions', 'Comprehensions'],
      ['errors-and-exceptions', 'Errors and exceptions'],
      ['debugging', 'Debugging'],
      ['modules', 'Modules and the standard library'],
      ['files-and-text', 'Files and text data'],
      ['classes-and-objects', 'Classes and objects'],
      ['special-methods', 'Special methods'],
      ['inheritance', 'Inheritance'],
      ['iterators-and-generators', 'Iterators and generators'],
      ['functions-as-values', 'Functions as values'],
      ['type-hints-and-dataclasses', 'Type hints and dataclasses'],
      ['testing-your-code', 'Testing your own code'],
    ]),

  series('ml', 'ml', 'ml', 'Machine Learning',
    'From NumPy to Q-learning, every core algorithm written from scratch first.', [
      ['numpy-arrays', 'NumPy arrays'],
      ['indexing-and-broadcasting', 'Indexing, shapes and broadcasting'],
      ['plotting', 'Plotting with matplotlib'],
      ['vectors', 'Vectors'],
      ['matrices-as-transformations', 'Matrices as transformations'],
      ['linear-systems', 'Solving linear systems'],
      ['eigenvectors-and-svd', 'Eigenvectors and SVD'],
      ['rates-of-change', 'Rates of change'],
      ['gradients-and-chain-rule', 'Gradients and the chain rule'],
      ['probability-by-simulation', 'Probability by simulation'],
      ['distributions', 'Distributions'],
      ['expectation-and-variance', 'Expectation and variance'],
      ['estimation-and-uncertainty', 'Estimation and uncertainty'],
      ['pandas-dataframes', 'pandas: DataFrames'],
      ['pandas-reshaping', 'pandas: reshaping and joining'],
      ['exploring-a-dataset', 'Exploring a dataset'],
      ['what-learning-is', 'What learning is'],
      ['least-squares', 'Linear regression by least squares'],
      ['loss-functions', 'Loss functions'],
      ['gradient-descent', 'Gradient descent'],
      ['multiple-regression', 'Multiple regression, vectorised'],
      ['overfitting', 'Overfitting and the bias–variance trade-off'],
      ['regularisation', 'Regularisation'],
      ['cross-validation', 'Validation and cross-validation'],
      ['perceptron', 'The perceptron'],
      ['perceptron-limits', 'What a perceptron cannot learn'],
      ['logistic-regression', 'Logistic regression'],
      ['classification-metrics', 'Classification metrics'],
      ['softmax-regression', 'Softmax regression'],
      ['knn', 'k-nearest neighbours'],
      ['naive-bayes', 'Naive Bayes'],
      ['decision-trees', 'Decision trees'],
      ['random-forests', 'Bagging and random forests'],
      ['boosting', 'Boosting'],
      ['svm', 'Support vector machines'],
      ['sklearn-workflow', 'The scikit-learn workflow'],
      ['feature-engineering', 'Feature engineering'],
      ['leakage-and-imbalance', 'Data leakage and imbalanced data'],
      ['hyperparameter-search', 'Hyperparameter search'],
      ['k-means', 'k-means'],
      ['hierarchical-and-dbscan', 'Hierarchical clustering and DBSCAN'],
      ['gaussian-mixtures', 'Gaussian mixtures and EM'],
      ['pca', 'PCA'],
      ['visualising-high-dimensions', 'Visualising high-dimensional data'],
      ['anomaly-detection', 'Anomaly detection'],
      ['neural-networks', 'From perceptron to neural network'],
      ['activation-functions', 'Activation functions'],
      ['backprop-by-hand', 'Backpropagation by hand'],
      ['autograd-engine', 'An automatic differentiation engine'],
      ['training-a-network', 'Training a network'],
      ['optimisers', 'Optimisers'],
      ['regularising-networks', 'Regularising networks'],
      ['convolution', 'Convolution'],
      ['cnns', 'Convolutional networks'],
      ['rnns', 'Recurrent networks'],
      ['lstm-and-gru', 'LSTM and GRU'],
      ['embeddings', 'Embeddings'],
      ['attention', 'Attention'],
      ['transformer-block', 'The transformer block'],
      ['autoencoders', 'Autoencoders'],
      ['generative-models', 'Generative models'],
      ['bayesian-inference', 'Bayesian inference'],
      ['time-series', 'Time series'],
      ['rl-problem', 'The reinforcement learning problem'],
      ['bandits', 'Multi-armed bandits'],
      ['mdps', 'Markov decision processes'],
      ['rl-dynamic-programming', 'Dynamic programming'],
      ['monte-carlo-rl', 'Monte Carlo methods'],
      ['td-and-sarsa', 'Temporal-difference learning and SARSA'],
      ['q-learning', 'Q-learning'],
      ['deep-q-learning', 'Deep Q-learning'],
      ['policy-gradients', 'Policy gradients'],
      ['interpreting-models', 'Interpreting models and checking them'],
      ['capstone', 'Capstone: from data to a defensible model'],
    ]),

  series('dsa', 'dsa', 'dsa', 'Algorithms & Design Patterns',
    'Data structures, algorithms and object design, taught together.', [
      ['what-an-algorithm-is', 'What an algorithm is'],
      ['big-o', 'Big-O'],
      ['cost-of-python-operations', 'The cost of Python operations'],
      ['amortised-analysis', 'Amortised analysis'],
      ['dynamic-arrays', 'Dynamic arrays'],
      ['linked-lists', 'Linked lists'],
      ['stacks', 'Stacks'],
      ['queues-and-deques', 'Queues and deques'],
      ['hash-tables', 'Hash tables'],
      ['sets-and-dict-patterns', 'Sets and dictionary patterns'],
      ['recursion', 'Recursion'],
      ['recurrences', 'Recurrences'],
      ['invariants', 'Invariants and correctness'],
      ['binary-search', 'Binary search'],
      ['elementary-sorts', 'Elementary sorts'],
      ['merge-sort', 'Merge sort'],
      ['quicksort', 'Quicksort and quickselect'],
      ['non-comparison-sorts', 'Sorting without comparisons'],
      ['binary-trees', 'Binary trees'],
      ['binary-search-trees', 'Binary search trees'],
      ['balanced-trees', 'Balanced trees'],
      ['heaps', 'Heaps and priority queues'],
      ['tries', 'Tries'],
      ['segment-and-fenwick-trees', 'Segment trees and Fenwick trees'],
      ['graph-representations', 'Graph representations'],
      ['bfs', 'Breadth-first search'],
      ['dfs', 'Depth-first search'],
      ['topological-sort', 'Topological sort'],
      ['dijkstra', "Dijkstra's algorithm"],
      ['bellman-ford-floyd-warshall', 'Bellman-Ford and Floyd-Warshall'],
      ['union-find', 'Union-Find'],
      ['minimum-spanning-trees', 'Minimum spanning trees'],
      ['a-star', 'A* search'],
      ['two-pointers', 'Two pointers'],
      ['sliding-window', 'Sliding window'],
      ['prefix-sums', 'Prefix sums'],
      ['monotonic-stacks', 'Monotonic stacks and queues'],
      ['divide-and-conquer', 'Divide and conquer'],
      ['greedy', 'Greedy algorithms'],
      ['dp-memoisation', 'Dynamic programming: memoisation'],
      ['dp-tabulation', 'Dynamic programming: tabulation'],
      ['dp-two-dimensions', 'Dynamic programming in two dimensions'],
      ['dp-state-design', 'Designing DP states'],
      ['backtracking', 'Backtracking'],
      ['bit-manipulation', 'Bit manipulation'],
      ['string-algorithms', 'String algorithms'],
      ['randomised-algorithms', 'Randomised algorithms'],
      ['why-design-matters', 'Why design matters'],
      ['single-responsibility', 'Single responsibility'],
      ['encapsulation-and-interfaces', 'Encapsulation and interfaces'],
      ['composition-over-inheritance', 'Composition over inheritance'],
      ['polymorphism', 'Polymorphism and duck typing'],
      ['solid', 'SOLID'],
      ['dependency-injection', 'Dependency inversion and injection'],
      ['refactoring', 'Refactoring'],
      ['strategy', 'Strategy'],
      ['factory-method', 'Factory method and simple factory'],
      ['abstract-factory', 'Abstract factory'],
      ['builder', 'Builder'],
      ['singleton', 'Singleton, and why to avoid it'],
      ['prototype', 'Prototype'],
      ['adapter', 'Adapter'],
      ['decorator', 'Decorator'],
      ['facade', 'Facade'],
      ['composite', 'Composite'],
      ['proxy', 'Proxy'],
      ['bridge', 'Bridge'],
      ['flyweight', 'Flyweight'],
      ['observer', 'Observer'],
      ['command', 'Command'],
      ['state', 'State'],
      ['template-method', 'Template method'],
      ['iterator', 'Iterator'],
      ['chain-of-responsibility', 'Chain of responsibility'],
      ['visitor', 'Visitor'],
      ['mediator', 'Mediator'],
      ['memento', 'Memento'],
      ['interpreter', 'Interpreter'],
      ['patterns-vs-simpler-python', 'Patterns vs simpler Python'],
      ['testing-algorithms', 'Testing algorithms'],
      ['profiling', 'Profiling and optimisation'],
      ['project-lru-cache', 'Project: LRU cache'],
      ['project-text-editor', 'Project: text editor with undo'],
      ['project-expression-evaluator', 'Project: expression evaluator'],
      ['project-job-scheduler', 'Project: job scheduler'],
      ['capstone-route-planner', 'Capstone: route planner'],
    ]),
]
