// ─── WPF project lessons ──────────────────────────────────────────────────────
//
// A WPF lesson's files (MainWindow.xaml, MainWindow.xaml.cs, view models...) are
// compiled together with a generated entry point: the launcher below, which opens the
// window for real, or the test program (dotnetTests.ts) plus the Ui helper below, which
// open the learner's MainWindow off-screen and run the lesson's tests against it.
// Both need the learner's window class to be LessonApp.MainWindow — the convention
// every WPF lesson follows. The project file itself is generated by the desktop app
// (desktop/app/runtimes/dotnet.cjs, PROJECT_TEMPLATES.wpf).
//
// Tests drive the window the way a person does, by x:Name, through the Ui class below.
// A click goes through Windows UI Automation (the accessibility API) rather than by
// raising Button.ClickEvent: checked on a real window, raising ClickEvent does not run
// a bound Command, while the automation Invoke runs the Click handler and the Command,
// and refuses a disabled button, as a real click would.


export const WPF_UI_KIT = String.raw`using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Automation.Peers;
using System.Windows.Automation.Provider;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Threading;

namespace LessonApp;

// Lets lesson tests use a real window the way a person would, by x:Name.
public static class Ui
{
    static readonly List<Window> openWindows = new();

    // Runs everything WPF has queued (bindings, layout, a click) before the test reads the screen.
    public static void Flush() =>
        Dispatcher.CurrentDispatcher.Invoke(() => { }, DispatcherPriority.Background);

    // Waits for work that finishes later (an awaited Task, a background thread reporting
    // back) while letting the UI thread keep running, as it would for a person waiting.
    // Returns whether the condition came true within the time limit.
    public static bool WaitUntil(Func<bool> condition, int timeoutMs = 5000)
    {
        var clock = System.Diagnostics.Stopwatch.StartNew();
        while (!condition())
        {
            if (clock.ElapsedMilliseconds > timeoutMs) return false;
            Flush();
            System.Threading.Thread.Sleep(10);
        }
        return true;
    }

    // Shows the window off-screen, without stealing focus, and returns it.
    public static T Open<T>() where T : Window, new()
    {
        var window = new T();
        window.ShowActivated = false;
        window.ShowInTaskbar = false;
        window.WindowStartupLocation = WindowStartupLocation.Manual;
        window.Left = -20000;
        window.Top = -20000;
        window.Show();
        openWindows.Add(window);
        Flush();
        return window;
    }

    public static T Find<T>(Window window, string name) where T : class
    {
        object? found = window.FindName(name);
        if (found == null)
            throw new Exception("No element named \"" + name + "\" in " + window.GetType().Name + " (give it x:Name=\"" + name + "\" in XAML, or RegisterName it in C#).");
        if (found is not T typed)
            throw new Exception("x:Name=\"" + name + "\" is a " + found.GetType().Name + ", but the test needs a " + typeof(T).Name + ".");
        return typed;
    }

    public static void Click(Window window, string name)
    {
        var button = Find<ButtonBase>(window, name);
        if (!button.IsEnabled)
            throw new Exception("\"" + name + "\" is disabled, so it can't be clicked.");
        var peer = UIElementAutomationPeer.CreatePeerForElement(button);
        if (peer.GetPattern(PatternInterface.Invoke) is IInvokeProvider invoke) invoke.Invoke();
        else if (peer.GetPattern(PatternInterface.Toggle) is IToggleProvider toggle) toggle.Toggle();
        else throw new Exception("\"" + name + "\" can't be clicked.");
        Flush();
    }

    public static void Type(Window window, string name, string text)
    {
        var box = Find<TextBox>(window, name);
        box.Text = text;
        // A TextBox binding normally copies its text to the source only when the box loses
        // focus; a person typing and then clicking elsewhere gets the same result.
        box.GetBindingExpression(TextBox.TextProperty)?.UpdateSource();
        Flush();
    }

    public static string Text(Window window, string name)
    {
        object element = Find<object>(window, name);
        switch (element)
        {
            case TextBlock block: return block.Text;
            case TextBox box: return box.Text;
            case ContentControl control: return control.Content?.ToString() ?? "";
            default: throw new Exception("x:Name=\"" + name + "\" is a " + element.GetType().Name + ", which has no text to read.");
        }
    }

    public static bool IsEnabled(Window window, string name) => Find<UIElement>(window, name).IsEnabled;

    public static bool IsVisible(Window window, string name) => Find<UIElement>(window, name).Visibility == Visibility.Visible;

    public static int ItemCount(Window window, string name) => Find<ItemsControl>(window, name).Items.Count;

    public static void Select(Window window, string name, int index)
    {
        Find<Selector>(window, name).SelectedIndex = index;
        Flush();
    }

    // Where an element is drawn, relative to the top-left of the window's content area, in
    // device-independent pixels (1/96 inch): for layout lessons.
    public static Rect Bounds(Window window, string name)
    {
        Flush();
        var element = Find<FrameworkElement>(window, name);
        var topLeft = element.TranslatePoint(new Point(0, 0), (UIElement)window.Content);
        return new Rect(topLeft, new Size(element.ActualWidth, element.ActualHeight));
    }

    // The colour of a brush property (Background, Foreground, BorderBrush, Fill...) of a named
    // element, as "#AARRGGBB", or the brush's type name when it isn't a solid colour: for
    // lessons on resources, styles and themes. The bytes are formatted here rather than with
    // Color.ToString(), which prints an animated colour as "sc#1, 0.02, ..." (measured after a
    // visual state's ColorAnimation).
    public static string Color(Window window, string name, string property = "Background")
    {
        Flush();
        var element = Find<FrameworkElement>(window, name);
        var info = element.GetType().GetProperty(property)
            ?? throw new Exception(element.GetType().Name + " \"" + name + "\" has no property " + property + ".");
        var value = info.GetValue(element);
        if (value is not System.Windows.Media.SolidColorBrush solid) return value?.GetType().Name ?? "null";
        var c = solid.Color;
        return "#" + c.A.ToString("X2") + c.R.ToString("X2") + c.G.ToString("X2") + c.B.ToString("X2");
    }

    // Resizes the window and lets layout run, as dragging its edge would.
    public static void Resize(Window window, double width, double height)
    {
        window.Width = width;
        window.Height = height;
        window.UpdateLayout();
        Flush();
    }

    public static void CloseAll()
    {
        foreach (var window in openWindows)
        {
            try { window.Close(); } catch { }
        }
        openWindows.Clear();
    }
}
`

export const WPF_LAUNCHER = `using System;
using System.Windows;

namespace LessonApp;

static class LessonLauncher
{
    [STAThread]
    static void Main() => new Application().Run(new MainWindow());
}
`
